import React from 'react';

export default function CfaDisinformation({ title, description, disInfoImg1, disInfoImg2, disInfoImg3 }) {

    return (
        <section className="disinformation py-5">
            <div className="container">
                <div className="content">
                    <h3 className="navy-text">{title}</h3>
                    <p className="my-3">{description}</p>
                </div>
                <div className="row justify-content-center mx-auto">
                    <div className="col-lg-4 col-sm-12">
                        <img
                            className="img-fluid"
                            src={disInfoImg1}
                            alt="Graphic showing 68% of Americans use social media to obtain information"
                        />
                    </div>
                    <div className="col-lg-4 col-sm-12">
                        <img
                            className="img-fluid"
                            src={disInfoImg2}
                            alt="Pie chart showing 20-25% of Twitter content has been generated by bots"
                        />
                    </div>
                    <div className="col-lg-4 col-sm-12">
                        <img
                            className="img-fluid"
                            src={disInfoImg3}
                            alt="Line graph showing percent trust in various information sources"
                        />
                    </div>
                </div>
            </div>
        </section>
    )
}
