import React from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import "bootstrap/dist/css/bootstrap.min.css";
import "../css/call-for-action.css";
import himg from "../images/illustrations/call-for-action-intro.png";
import panel1 from "../images/Call For Action/Disinfo-card1.png";
import panel2 from "../images/Call For Action/Disinfo-card2.png";
import panel3 from "../images/Call For Action/Disinfo-card3.png";
import roadmap from "../images/Call For Action/CFA - Diag3.png";
import { faCaretDown } from "@fortawesome/free-solid-svg-icons";

const CfA = () => {
  return (
    <>
      <div>
        <div className="container illustration-header d-flex align-items-center">
          <div className="content">
            <h4>Call For Action</h4>
            <br />
            <p style={{ color: "black" }}>
              The Call For Action team is calling innovators, engineers,
              sociologists, and scientists to address social issues in the
              technology industry and help us curate innovations to solve these
              critical social problems. With your support, ideas, and
              innovations, we can do it!
            </p>
            <p style={{ color: "black" }}>
              We are at an early stage of developing this program, please join a
              fun, passionate team to tackle the social crisis in the Technology
              Industry.
            </p>
          </div>
          <img className="img-fluid" src={himg} />
        </div>
        {/* Vision / Mission */}
        <section className="header-goal">
          <div className="container">
            <div className="row">
              <div className="col-12 col-lg-6">
                <div className="row align-items-center row-height">
                  <h5 className="col-3 navy-text">VISION</h5>
                  <p className="col-9 ">
                    Address social issues in the Tech industry and curate
                    innovations to solve critical social problems.
                  </p>
                </div>
              </div>
              <div className="col-12 col-lg-6">
                <div className="row align-items-center row-height">
                  <h5 className="col-3 navy-text">MISSION</h5>
                  <p className="col-9 ">
                    We aim to create processes and systems supported by emerging
                    technologies with collaboration of industry and technology
                    experts.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* Disinformation */}
        <section className="disinformation py-5">
          <div className="container">
            <div className="content">
              <h3 className="navy-text">DISINFORMATION</h3>
              <p className="my-3">False information intended to mislead</p>
            </div>
            <div className="row justify-content-center mx-auto">
              <div className="col-lg-4 col-sm-12">
                <img
                  className="img-fluid"
                  src={panel1}
                  alt="Graphic showing 68% of Americans use social media to obtain information"
                />
              </div>
              <div className="col-lg-4 col-sm-12">
                <img
                  className="img-fluid"
                  src={panel2}
                  alt="Pie chart showing 20-25% of Twitter content has been generated by bots"
                />
              </div>
              <div className="col-lg-4 col-sm-12">
                <img
                  className="img-fluid"
                  src={panel3}
                  alt="Line graph showing percent trust in various information sources"
                />
              </div>
            </div>
          </div>
        </section>
        {/* Road Map */}
        <section style={{ backgroundColor: "white" }} className="road-map py-5">
          <div className="container">
            <div className="content">
              <h3 className="mb-5 navy-text">ROADMAP</h3>
              <img
                className="pb-5 mx-auto"
                src={roadmap}
                alt="Image of Call For Action roadmap"
              />
              <div className="pt-5 row pb-5">
                <div className="col-md-auto pr-0">
                  <FontAwesomeIcon
                    icon={faCaretDown}
                    style={{ color: "#AF8661", fontSize: "2rem" }}
                  />
                </div>
                <div className="col-md-auto">
                  <p className="phase">Phase I</p>
                </div>
                <div className="col-10">
                  <p className="phase-title">Analysis</p>
                  <p className="phase-q">June 2021 - September 2021</p>
                  <p>
                    During the first phase of the program, we brought forward
                    the key social issues in Technology. With the help of root
                    cause analysis based on the fishbone diagram and 8 why
                    framework, we listed the major pain points addressing these
                    issues. We identified our first workstream project -
                    Disinformation.
                  </p>
                </div>
              </div>
              <div className="row pb-5">
                <div className="col-md-auto pr-0">
                  <FontAwesomeIcon
                    icon={faCaretDown}
                    style={{ color: "#AF8661", fontSize: "2rem" }}
                  />
                </div>
                <div className="col-md-auto">
                  <p className="phase">Phase II</p>
                </div>
                <div className="col-10">
                  <p className="phase-title">Solution Discussion</p>
                  <p className="phase-q">October 2021 - January 2022</p>
                  <p>
                    Based on the analysis phase, the solution discussion is
                    divided into two tracks:
                    <br />
                    Track 1 - Legislation: Introduction of new policies
                    <br />
                    Track 2 - Technology Platform: Develop a platform with
                    emerging Technology, such as AI, AR, VR, and NLP-based
                    solutions to identify and label disinformation
                  </p>
                </div>
              </div>
              <div className="row pb-5">
                <div className="col-md-auto pr-0">
                  <FontAwesomeIcon
                    icon={faCaretDown}
                    style={{ color: "#AF8661", fontSize: "2rem" }}
                  />
                </div>
                <div className="col-md-auto">
                  <p className="phase">Phase III</p>
                </div>
                <div className="col-10">
                  <p className="phase-title">
                    Solution Development / Prototype{" "}
                  </p>
                  <p className="phase-q">January 2022 - June 2022</p>
                  <p>
                    Develop prototypes for Legislation &amp; Technology Platform
                    <br />
                    Explore fundraising, partnerships, and collaboration
                    opportunities
                  </p>
                </div>
              </div>
              <div className="row pb-5">
                <div className="col-md-auto pr-0">
                  <FontAwesomeIcon
                    icon={faCaretDown}
                    style={{ color: "#AF8661", fontSize: "2rem" }}
                  />
                </div>
                <div className="col-md-auto">
                  <p className="phase">Phase IV</p>
                </div>
                <div className="col-10">
                  <p className="phase-title">Solution Deployment</p>
                  <p className="phase-q">June 2022 onwards</p>
                  <p>Take phased approach for global deployment</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </>
  );
};

export default CfA;
