const podcastData = [
    {
        "id": 9,
        "guestName": "Kevin Liu Huang(HU '13)",
        "guestTitle": "MBA Candidate - Stanford",
        "description": "Kevin Liu Huang is an MBA student at Stanford. He's also an officer in the Marine Corps reserves and aspires to entrepreneurship. He graduated from Harvard College in 2013 with a joint concentration in Statistics and Government, and he runs a newsletter called Chiral Defense.",
        "episode": "9",
        "createdAt": "2022",
        "image_url": "https://res.cloudinary.com/dlz977spb/image/upload/v1662875683/Hi_TS_Podcast_Kevin_Liu_Huang_Flyer_943e467a8e.png",
        "image_alt": "HiTS Podcast Kevin Liu Huang Flyer.png",
        "spotify": "https://open.spotify.com/episode/0QJ0JTMlOco9J3SxBl05n1?si=aef6a941de43495f",
        "soundCloud": "https://soundcloud.com/user-616895977/episode-9-kevin-liu-huang",
        "apple": "https://podcasts.apple.com/us/podcast/episode-9-kevin-liu-huang/id1547518984?i=1000556185475"
    },
    {
        "id": 8,
        "guestName": "Fatoumata Fall (HU '14)",
        "guestTitle": "Co-Founder Goodness Green",
        "description": "Fatou Fall is a STEM advocate and an entrepreneur from Senegal. She's currently building a hydroponics startup called Goodness Green for the Sahel region. Prior to that, she co-founded a US-based negotiation company for high-achieving scientists and engineers, got featured on the Forbes 30 under 30 List, and was on the founding team of African Leadership University. Fatou graduated from Harvard University with a degree in Applied Mathematics.",
        "episode": "8",
        "createdAt": "2022",
        "image_url": "https://res.cloudinary.com/dlz977spb/image/upload/v1662875185/Hi_TS_Podcast_Fatoumata_Fall_Flyer_d6ad3897c1.png",
        "image_alt": "HiTS Podcast Fatoumata Fall Flyer.png",
        "spotify": "https://open.spotify.com/episode/0TnoLtCTu3ohjfFcMylBJs?si=b0891f15ef844674",
        "soundCloud": "https://soundcloud.com/user-616895977/harvard-in-tech-seattle-podcast-episode-8-fatou-fall",
        "apple": "https://podcasts.apple.com/us/podcast/harvard-in-tech-seattle-podcast-episode-8-fatou-fall/id1547518984?i=1000545774447"
    },
    {
        "id": 7,
        "guestName": "My Le Goel (HU '04)",
        "guestTitle": "CEO and Founder Flight Live Inc.",
        "description": "My Le is the CEO of FlightLive, a mobile wellness technology platform for living, interactive, virtual personal fitness training that matches clients with a curated list of certified personal trainers and yoga instructors.",
        "episode": "2",
        "createdAt": "2021",
        "image_url": "https://res.cloudinary.com/dlz977spb/image/upload/v1660590839/Hi_TS_Podcast_My_Le_Goel_3d7c71c590.png",
        "image_alt": "HiTS Podcast My Le Goel.png",
        "spotify": "https://open.spotify.com/episode/2JXKfaj3Fx7WxS0M1EAGjt?si=_xGFmJE2QSuu2O_ju0f5yQ&dl_branch=1",
        "soundCloud": "https://soundcloud.com/user-616895977/my-le-goel",
        "apple": "https://podcasts.apple.com/us/podcast/harvard-in-tech-seattle-podcast-episode-2-my-le-goel/id1547518984?i=1000504437918"
    },
    {
        "id": 6,
        "guestName": "Steven Maheshwary (HU '12)",
        "guestTitle": "Director of Economic Development - IT, Washington State",
        "description": "Steven Maheshwary is a tech industry veteran who is passionate about the nexus of tech and positive social impact through fostering entrepreneurship, building partnerships, and empowering communities.",
        "episode": "1",
        "createdAt": "2021",
        "image_url": "https://res.cloudinary.com/dlz977spb/image/upload/v1660590119/Hi_TS_Podcast_Steven_Maheshwary_d389a5ff9b.png",
        "image_alt": "HiTS Podcast Steven Maheshwary.png",
        "spotify": "https://open.spotify.com/episode/4XMFIFruYPtJJvuSWhPT03?si=lwgF90WxST6tXhtmp1YnZA&dl_branch=1",
        "soundCloud": "https://soundcloud.com/user-616895977/harvard-in-tech-seattle-podcast-episode-1-steven-maheshwary",
        "apple": "https://podcasts.apple.com/us/podcast/harvard-in-tech-seattle-podcast-episode-1-steven-maheshwary/id1547518984?i=1000504437919"
    },
    {
        "id": 5,
        "guestName": "Bridget Frey (HU '99)",
        "guestTitle": "Chief Technology Officer Redfin",
        "description": "As Redfin's Chief Technology Officer, Bridget leads the software engineering team, which she has grown to more than 150 engineers in Seattle and San Francisco.",
        "episode": "3",
        "createdAt": "2021",
        "image_url": "https://res.cloudinary.com/dlz977spb/image/upload/v1660412432/Hi_TS_Podcast_Bridget_Frey_3a856cf115.png",
        "image_alt": "HiTS Podcast Bridget Frey.png",
        "spotify": "https://podcasts.apple.com/us/podcast/harvard-in-tech-seattle-podcast-episode-3-bridget-frey/id1547518984?i=1000507775956",
        "soundCloud": "https://soundcloud.com/user-616895977/episode-3-bridget-frey",
        "apple": "https://podcasts.apple.com/us/podcast/harvard-in-tech-seattle-podcast-episode-3-bridget-frey/id1547518984?i=1000507775956"
    },
    {
        "id": 4,
        "guestName": "Laura Butler",
        "guestTitle": "CEO and Co-founder UpLift Group Inc.",
        "description": "Laura Butler is the Co-founder and CEO/CTO of UpLift Group. She is also an amateur angel and LP who takes a fairy godmother approach.",
        "episode": "4",
        "createdAt": "2022",
        "image_url": "https://res.cloudinary.com/dlz977spb/image/upload/v1660412040/Hi_TS_Podcast_Laura_Butler_3525413ecc.png",
        "image_alt": "HiTS Podcast Laura Butler.png",
        "spotify": "https://open.spotify.com/episode/16L6HOcGMMgqDGNcE6ZaX3?si=s4eCouVfQq-1HeN9X4XxJg&dl_branch=1",
        "soundCloud": "https://soundcloud.com/user-616895977/harvard-in-tech-seattle-podcast-episode-4-laura-butler",
        "apple": "https://podcasts.apple.com/us/podcast/harvard-in-tech-seattle-podcast-episode-4-laura-butler/id1547518984?i=1000510594113"
    },
    {
        "id": 3,
        "guestName": "Aran Khanna (HU '16)",
        "guestTitle": "CEO and Co-founder Reserved.ai",
        "description": "Aran Khanna is co-founder and CEO of Reserved.ai. He graduated from Harvard College in 2016. He has previously worked at several startups, one of which was acquired by Amazon Web Services (AWS). One of the principles he follows and explains in this episode is extreme ownership.",
        "episode": "5",
        "createdAt": "2022",
        "image_url": "https://res.cloudinary.com/dlz977spb/image/upload/v1660411819/Hi_TS_Podcast_Aran_Khanna_0473a0fdbc.png",
        "image_alt": "HiTS Podcast Aran Khanna.png",
        "spotify": "https://open.spotify.com/episode/7DM8S55UZRGq93QNKMAQoP?si=FIVxEUHVSS6LAY0sefP-AQ&dl_branch=1",
        "soundCloud": "https://soundcloud.com/user-616895977/episode-5-aran-khanna",
        "apple": "https://podcasts.apple.com/us/podcast/harvard-in-tech-seattle-podcast-episode-5-aran-khanna/id1547518984?i=1000520002062"
    },
    {
        "id": 2,
        "guestName": "Ziad Ismail (HBS '04)",
        "guestTitle": "Chief Product Officer Convoy",
        "description": "Ziad Ismail is the Chief Product Officer of Convoy. Before Convoy, Ziad was the Chief Product Officer of Marchex, Chief Executive Officer of CitiKey, and served in other leadership roles at Microsoft. Ziad earned an MBA from Harvard Business School. The key takeaways from the podcast are key insights into the logistics in the transportation industry, and how work ethic and curiosity are underrated.",
        "episode": "7",
        "createdAt": "2022",
        "image_url": "https://res.cloudinary.com/dlz977spb/image/upload/v1660411046/Hi_TS_Podcast_Ziad_Ismail_7f38520437.png",
        "image_alt": "HiTS Podcast Ziad Ismail.png",
        "spotify": "https://open.spotify.com/episode/21zx9bZemsy1x2CpBtBNmB?si=ORSDiWtlRaW9YlIlrMbLhw",
        "soundCloud": "https://soundcloud.com/user-616895977/episode-7-ziad-ismail",
        "apple": "https://podcasts.apple.com/us/podcast/harvard-in-tech-seattle-podcast-episode-7-ziad-ismail/id1547518984?i=1000539813540"
    },
    {
        "id": 1,
        "guestName": "Spencer Rascoff (HU '97)",
        "guestTitle": "Co-founder & Chair Pacaso, Supernova SPAC, dot.LA",
        "description": "Spencer Rascoff is the CEO of Pacaso. He was previously the CEO of Zillow for over 13 years as well as co-founding and/or being a board member of many other companies e.g. dot.LA, Palantir, 75 & Sunny, etc.",
        "episode": "6",
        "createdAt": "2022",
        "image_url": "https://res.cloudinary.com/dlz977spb/image/upload/v1660264318/tech_in_us_defense_flyer_7980ffcee1.png",
        "image_alt": "Spencer-Rascoff.png",
        "spotify": "https://open.spotify.com/episode/7DM8S55UZRGq93QNKMAQoP?si=FIVxEUHVSS6LAY0sefP-AQ&dl_branch=1\",",
        "soundCloud": "https://soundcloud.com/user-616895977/episode-5-aran-khanna",
        "apple": "https://podcasts.apple.com/us/podcast/harvard-in-tech-seattle-podcast-episode-5-aran-khanna/id1547518984?i=1000520002062"
    }
]
export default podcastData